[package]
name = "par-validator"
version = "0.1.0"
edition = "2024"
description = "A truely parallel field validator engine written on top of ryon, wgpu and rust-key-paths."
readme = "../README.md"
license = "MIT"
keywords = ["validation", "rayon", "wgpu", "fintech", "keypath"]
categories = ["concurrency"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
rayon = "1.11.0"
rust-key-paths = { version = "2.9.2" }
wgpu = "22"

[dev-dependencies]
key-paths-derive = "2.4"